
services:
  postgres:
    image: postgres
    container_name: lab-container

    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local